schema.sql

1. Set up the database schema
2. run on the mariadb and it works totally fine

Setup the Database Schema

---

db/config.php
db/user_setup.sql

create new php and sql files for being used in travis testing

create new php and sql files for being used in travis testing

---

.travis.yml
package.json
src/App.vue
src/base64js.min.js
src/main.js
src/views/edit-courses.vue
src/views/question-select.vue
src/views/settings.vue
src/views/survey-release.vue
src/views/ta-results-permission.vue
src/views/ta-results.vue

Prettier checks all .vue files in src/views folder.
#5

travis setup running mock server, mariadb,mocha test and prettier check

---

db/db_data.sql
db/schema.sql

1. Create data instances (db_data.sql)
2. revise table schema(schema.sql)
Note: db_data.sql is for testing purposes.

Create data instances and revise table schema

---

backend_testing/test.js

This file is a structure for the testing, and it is not complete. The reason that I make this Pull Request is that after being merged, Daniel and I can separate the testing cases in this file and work on the same file from now.

Set up the structure for the API PHP testing for TA_Feedback 

---

db/schema.sql

1. Add the foreign key constraints 2. Make the attribute names uniform
(Already tests on MariaDB and it works)

Schema Improvement

---

db/schema.sql

1. change "default_time_window" to "default_survey_open"
2. change "default_start_time" to "default_survey_close"
3. Set their variable types as DATETIME

Set variable name to "default_survey_open" and "default_survey_close" to make it uniform with "survey_open" and "survey_close"

---

db/generate_sample_data.py
db/sample_data.sql

Note: these two files will only work for the newly revised schema in pull request

finish the script python file for data generating and tests OK 

---

db/schema.sql

In this schema update, we:
1. Refactored tables relating to question choices to allow easier access of question choices for each survey and allow easy access of locked questions when revising survey. 
2. Refactored users table to allow user to take on multiple roles.
3. Added parent column in surveys to allow hierarchical access of surveys and distinguishing child surveys easier.
4. Removed foreign key reference from response table to users table for user_id, this is because we don't need to store students info in our users table.

Schema update

---

src/App.vue
src/css/app.css
src/views/components/errorBlock.vue
src/views/components/navbar.vue

Red block appears at top of page with error message.
All components must implement `this.$emit('error', message)` where message is the error message.
This method sends the error message back to the parent component.

Implemented error component

---

src/App.vue
src/main.js
src/views/components/survey_components/question_time_setting.vue
src/views/components/survey_components/survey_list.vue
src/views/surveys.vue

This view integrates successfully with the 'GET' API

finish the surveys view 

---

README.md
package.json

removed parser specification for prettier config, added prettier procedures in README file, removed prettier test script with mocha

README update and Prettier config changes

---

src/views/course_pairings.vue
test/course_pairings.spec.js

Test course pairings component

---

src/views/components/survey_components/question_time_setting.vue
src/views/surveys.vue
test/question_time_setting.spec.js

- Change all indexOf to check by value
- Move API data parsing to separate function
- Handled unhandled API error by calling error component
fixes #81 
fixes #83

Test Survey Component

---

get_query_generators.php

fixed a bug where survey results was not retrieved despite target_ta was related to the user.

API bug fix

---

package-lock.json
package.json
src/main.js
src/views/student-surveys.vue

Implemented student survey component

---

get_info.php

fixed an index out of bound error when requesting for responses of a survey

GET API bug fix

---

student_survey.php
survey_query_generators.php
webpack.config.js

Implemented student view component

---

src/main.js
src/views/student-surveys.vue
student_survey.php

Implement GET and POST call in student survey component

---

post_info.php

1. "gen_query_get_choices_id" returns an array, so check $level attribute to determine which element to use in the array
2. add attribute $data needed in "handle_survey_update"

fixes survey update

---

post_info.php
src/views/settings.vue

Send new user info to database

---

student_survey.php

Fix POST input stream

---

.travis.yml
package.json
webpack.config.js

Now directly using UglifyJsPlugin and specified ecma version up to 8

fixed npm build error

---

src/main.js
src/views/student-landing.vue

Student landing page

---

get_info.php
get_query_generators.php
src/views/course_pairings.vue
test/front_end/course_pairings.spec.js

-POST new cell changes to database
-Implement ability to delete user association
-Display table with rows of different number of columns
-Include section_id with GET call
fixes #104

Implemented POST Call for Course Pairings

---

package-lock.json
package.json
src/main.js
webpack.config.js

fixes #132 
Decision based on:
- Documentation of Library
- Contributors
- Community Size
Vuetify beats Bootstrap-Vue and Material-Vue

Added Vuetify as an UI library

---

post_info.php

(If `action=add_or_update`, the API will check whether the survey has
already been set before; If not, a new survey will be branched first and
then update on the newly branched survey)
fixes #129

Udpate the "survey update" functionality

---

src/views/student-landing.vue
student_survey.php
survey_query_generators.php

-detect when student has already submitted answers for selected question
-allows user to override past answers or submit responses for new survey
fixes #131

Enable Student Answer Override

---

db/schema.sql

Add "viewable_by_others" (bit type) attribute in the survey_instance table 
fixes #127

schema change to allow the prof and admin to view the survey result

---

test/back_end/api_student_survey_test.spec.js

Test GET functions for student API

---

src/views/components/response_components/select_ta.vue
src/views/components/response_components/summary_widget.vue
src/views/components/response_components/survey_summary.vue
src/views/components/survey_wrapper.vue
src/views/settings.vue

Tested the survey_wrapper idea, will make another PR to clean this up. Currently working with the Results Page.

Added survey wrapper component

---

post_info.php
post_query_generators.php
test/back_end/api_post_test.spec.js

1. fix the functionality of survey update on the case "branch first and then update"
2. add test for "branch first and then update"

Update post API and add more test

---

src/views/components/survey_components/question_selection.vue
src/views/components/survey_components/question_time_setting.vue
src/views/redirect.vue
test/front_end/question_time_setting.spec.js

1. Separate "QuestionList" out from the "question_time_setting" page.
2. revise the according test
3. change the user_id example in redirect.vue into "woods13"
fixes #153

Separate "QuestionList" out into a single component

---

src/views/components/response_components/survey_summary.vue
src/views/components/response_components/survey_wrapper.vue

- Dropdown for survey instances now show only text based responses

now survey instances dropdown shows only text responses

---

src/App.vue
src/views/components/response_components/launch-modal.vue
src/views/components/response_components/survey_wrapper.vue

Implemented launch modal

---

src/views/components/course_list.vue
src/views/components/get_unique_attribute.js
src/views/dashboard.vue

Stubbed list of courses in dashboard and removed survey component from dashboard
fixes #130

Stubbed last component

---

src/views/components/response_components/response.vue
src/views/components/response_components/survey_wrapper.vue
src/views/components/survey_components/survey_list.vue

Added selection of view mode for surveys

---

db/schema.sql

1. change the attribute "term" from type "INT" into type "VARCHAR"
2. change the attribute "viewable_by_others" from type "bit" into "INT"
3. change attributes "is_admin", "is_instructor", "is_ta" into type "INT"
fixes #171

Change the type of attributes in schema

---

src/views/components/navbar.vue

Remove settings button and set home button to dashboard

Set navbar links to new urls

---

src/views/components/response_components/survey_instance.vue
src/views/components/response_components/survey_instance_list.vue
src/views/components/response_components/survey_summary.vue
src/views/components/survey_components/survey_list.vue

removed loading display for individual surveys, added loading for all survey_instance_list and survey_list component

Updated loading for surveys and results page

---

src/main.js

Shibboleth blocks requests that aren't sent with credentials. This ensures `fetch` sends credentials.

Monkeypatch `fetch` to always include credentials

---

src/css/app.css

included styling for SurveyJS component

---

src/views/components/response_components/survey_wrapper.vue
src/views/components/survey_components/question_selection.vue
test/.setup.js
test/front_end/question_time_setting.spec.js.no-use

Integrated question_selection component with edit button for survey component.
Updated select_questions component, removed many irrelevant functions.
*Added fixes for front-end test so that test will not fail if used.

Added Question Selection Component

---

post_info.php
test/back_end/api_post_test.spec.js

1. Convert all the "data" into "DATA" in the returning data of the API
2. Change the "viewable_by_others" post API

convert all the "data" into "DATA" in returning data of the API

---

post_info.php

Add comments 

---

post_info.php

`handle_survey_update` was using the `choice_id` as the `*_choices_id` (e.g., the `ta_choices_id`). Now we get the `*_choices_id` and grab its referenced `choices_id`.

Fix bugs in `handle_survey_update`

---

src/views/components/survey_components/survey_list.vue

variable declaration

---

test/back_end/api_post_test.spec.js

Add tests to include the cases where some of the attributes are null or all the attributes are null in the data package sent to the "survey update" post API

Add test cases when attributes are null to "survey update" API

---

src/views/components/response_components/launch-modal.vue

POST modified start and end time

---

test/back_end/api_get_test.spec.js
test/back_end/api_post_test.spec.js
test/back_end/api_student_survey_test.spec.js

Add the query string generator in back end test files

---

src/views/components/response_components/survey_display.vue
src/views/results.vue

Display override token for survey instances

---

post_info.php

return survey package in the "survey_settings" post API
fixes #223

Change the return data "survey_settings" post API

---

get_info.php
src/views/components/generate_query_string.js
test/back_end/api_post_test.spec.js

ignore `null` params for term and course

Removed sending null params

---

src/views/components/response_components/survey_display.vue
src/views/components/survey_components/survey_list.vue
src/views/components/survey_components/token_modal.vue

Hide clone button
Change cancel button on token modal to ok
Hide override token if not survey instance

UI Refactor

---

test/back_end/api_post_test.spec.js

Add post tests to check a new survey is generated when "branch first and then update"

Add more post API tests

---

get_info.php
post_info.php
src/views/redirect.vue
utils.php

Insert utorid in URL
Check if utorid and user_id match on every query

Implemented shibboleth

---

php/get_info.php
php/query_utils.php

Insert new TA into database if utorid does not exist within database.
fixes #212

Insert new TA into db

---

src/ta_main.js
src/views/components/course_list.vue
src/views/components/launch_modal.vue
src/views/components/navbar.vue
src/views/components/user_info.vue
src/views/course_pairings.vue
src/views/redirect.vue
src/views/surveys.vue

Paramterized ta routes

---

php/get_info.php
php/query_utils.php
test/back_end/api_get_test.spec.js

Updated according to API documentation.
Currently don't deal with users with multiple roles, the higher role takes precedence as of now

updated GET API for what=surveys

---

src/App.vue
src/css/app.css
src/views/components/navbar.vue

Replace side nav with top header

---

db/generate_sample_data.py
db/test_data.sql
test/back_end/api_get_test.spec.js

Added tests for what=survey_results.
Wrapped API test under another layer describing the `what` param being tested

added tests and fixed bug in crafted data

---

src/views/components/launch_modal.vue
src/views/components/survey_question_editor.vue
src/views/components/token_modal.vue

Updated button style in dialogs

---

src/views/components/name_modal.vue

Rename emit function to allow name modal to be cancelled

Rename function for emit

---

src/views/surveys.vue

Refresh data after new user saves name
